### ISSUE TITLE
Error 3

### ISSUE THREAD

**Issue by WildEgo** [supergrecko/RiotQuest#57]
**Describe the bug**
I have no idea

**Expected behavior**
Not Error: 3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PHP Version 7.2.10
 - RiotQuest Version 1.3.6

**Additional context**
```
[2019-09-22 16:58:58] local.INFO: A RiotQuest LeagueException has been thrown.
             Match the given error code with the ones described 
             at (https://riotquest.supergrecko.dev/docs/exceptions/) 
             for a more verbose description.
             
             ERROR (code 3): Internal Service Error. Please report this error by opening an issue on GitHub.
```

**Comment by supergrecko** [comment]
Assuming this is a log (that's what it looks like) it's basically impossible to trace it back (which is my fault for not thinking about this case).

I'll work on trying to find a better way to throw these exceptions as well as #56 over the next few days.

**Comment by WildEgo** [comment]
Cache related it looks like
```
#0 E:\XAMPP\htdocs\******\vendor\supergrecko\riot-quest\src\RiotQuest\Components\Engine\Request.php(157): Symfony\Component\Cache\CacheItem->expiresAfter(150) #1 E:\XAMPP\htdocs\******\vendor\symfony\cache\LockRegistry.php(87): RiotQuest\Components\Engine\Request->RiotQuest\Components\Engine\{closure}(Object(Symfony\Component\Cache\CacheItem), true) #2 E:\XAMPP\htdocs\******\vendor\symfony\cache\Traits\ContractsTrait.php(88): Symfony\Component\Cache\LockRegistry::compute(Object(Closure), Object(Symfony\Component\Cache\CacheItem), true, Object(Symfony\Component\Cache\Adapter\FilesystemAdapter), Object(Closure), NULL) #3 E:\XAMPP\htdocs\******\vendor\symfony\cache-contracts\CacheTrait.php(68): Symfony\Component\Cache\Adapter\AbstractAdapter->Symfony\Component\Cache\Traits\{closure}(Object(Symfony\Component\Cache\CacheItem), true) #4 E:\XAMPP\htdocs\******\vendor\symfony\cache\Traits\ContractsTrait.php(95): Symfony\Component\Cache\Adapter\AbstractAdapter->doGet(Object(Symfony\Component\Cache\Adapter\FilesystemAdapter), 'cfe89021ed82a0d...', Object(Closure), 1, Array, NULL) #5 E:\XAMPP\htdocs\******\vendor\symfony\cache-contracts\CacheTrait.php(30): Symfony\Component\Cache\Adapter\AbstractAdapter->doGet(Object(Symfony\Component\Cache\Adapter\FilesystemAdapter), 'cfe89021ed82a0d...', Object(Closure), 1, Array) #6 E:\XAMPP\htdocs\******\vendor\supergrecko\riot-quest\src\RiotQuest\Components\Engine\Request.php(223): Symfony\Component\Cache\Adapter\AbstractAdapter->get('cfe89021ed82a0d...', Object(Closure)) #7 E:\XAMPP\htdocs\******\vendor\supergrecko\riot-quest\src\RiotQuest\Components\Engine\Request.php(105): RiotQuest\Components\Engine\Request->finalize() #8 E:\XAMPP\htdocs\******\vendor\supergrecko\riot-quest\src\RiotQuest\Components\Endpoints\Summoner.php(55): RiotQuest\Components\Engine\Request->send() #9 E:\XAMPP\htdocs\******\app\Http\Controllers\Booster----Controller.php(89): RiotQuest\Components\Endpoints\Summoner->name('CalvinYap') #10 [internal function]: App\Http\Controllers\Booster----Controller->index('633') #11 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): call_user_func_array(Array, Array) #12 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('index', Array) #13 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Booster----Controller), 'index') #14 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Route.php(176): Illuminate\Routing\Route->runController() #15 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Router.php(680): Illuminate\Routing\Route->run() #16 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #17 E:\XAMPP\htdocs\******\app\Http\Middleware\isLegitimateBooster.php(20): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #18 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): App\Http\Middleware\isLegitimateBooster->handle(Object(Illuminate\Http\Request), Object(Closure)) #19 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #20 E:\XAMPP\htdocs\******\app\Http\Middleware\is----Booster.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #21 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): App\Http\Middleware\is----Booster->handle(Object(Illuminate\Http\Request), Object(Closure)) #22 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #23 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #24 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure)) #25 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #26 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #27 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure)) #28 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #29 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(75): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #30 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure)) #31 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #32 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #33 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #34 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #35 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #36 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #37 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #38 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #39 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure)) #40 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #41 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #42 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure)) #43 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #44 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #45 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Router.php(682): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #46 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Router.php(657): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request)) #47 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Router.php(623): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route)) #48 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Router.php(612): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) #49 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #50 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request)) #51 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #52 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure)) #53 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #54 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #55 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure)) #56 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #57 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #58 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure)) #59 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #60 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #61 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure)) #62 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #63 E:\XAMPP\htdocs\******\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #64 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure)) #65 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #66 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #67 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #68 E:\XAMPP\htdocs\******\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request)) #69 E:\XAMPP\htdocs\******\public\index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request)) #70 {main}
```
